--- #YAML:1.0
name:               WebService-GData
version:            0.0101
abstract:           represent a base GData object.
author:
    - A. U. Thor <a.u.thor@a.galaxy.far.far.away>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
