# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-GData
version:      0.0303
version_from: lib/WebService/GData.pm
installdirs:  site
requires:
    JSON:                          2
    LWP:                           0
    Test::Mock::LWP:               0.05
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
